version: "3"

services:
  app:
    container_name: app
    restart: always
    build: .
    environment: 
      - PORT=3000 
    ports: 
      - "3000:3000" 
    links: 
      - postgres
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: asdqwe123